server:
  port: 8081

spring:
  application:
    name: ekko-auth
  datasource:
    url: jdbc:postgresql://localhost:5435/authdb
    username: ekko
    password: ekko
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

jwt:
  secret: ekkosecretkey1234567890ekkosecretkey1234567890ekkosecretkey1234567890
  expiration: 86400000